sudo: required
services:
  - docker

before_install:
  - docker build -t renanssantos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true renanssantos/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "aws-elasticbeanstalk-service-role"
  env: "Aws-elasticbeanstalk-service-rol-env"
  bucket_name: "elasticbeanstalk-us-east-2-157978022792"
  bucket_path: "aws-elasticbeanstalk-service-role"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
